/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversorsrc;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Usuario
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tipoDeConversion = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        panelResultado1 = new javax.swing.JPanel();
        panelResultado2 = new javax.swing.JPanel();
        valorInicial = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        valorFinal = new javax.swing.JLabel();
        valorEntrada = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        panelBtn1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(500, 300));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 300));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(233, 232, 248));
        jPanel5.setMinimumSize(new java.awt.Dimension(500, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled Project.jpg"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jPanel1.setBackground(new java.awt.Color(233, 232, 248));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BIENVENIDO AL SISTEMA");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("POR FAVOR SELECCIONE");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("EL TIPO DE CONVERSION");

        tipoDeConversion.setBackground(new java.awt.Color(233, 232, 248));
        tipoDeConversion.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tipoDeConversion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COP a Dólar", "Dólar a COP", "COP a Euro", "Euro a COP", "COP a Libras Esterlinas", "Libras Esterlinas a COP", "COP a Yen Japonés", "Yen Japonés a COP", "COP a Won sul-coreano", "Won sul-coreano a COP" }));
        tipoDeConversion.setBorder(null);
        tipoDeConversion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tipoDeConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDeConversionActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(tipoDeConversion, 0, 168, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tipoDeConversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panelResultado1.setBackground(new java.awt.Color(233, 232, 248));
        panelResultado1.setPreferredSize(new java.awt.Dimension(162, 136));

        panelResultado2.setBackground(new java.awt.Color(233, 232, 248));
        panelResultado2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 89, 108)));
        panelResultado2.setForeground(new java.awt.Color(255, 89, 108));

        valorInicial.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        valorInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorInicial.setText("VALOR INICIAL");
        valorInicial.setPreferredSize(new java.awt.Dimension(88, 16));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled Project (1).jpg"))); // NOI18N

        valorFinal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        valorFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorFinal.setText("VALOR FINAL");
        valorFinal.setPreferredSize(new java.awt.Dimension(88, 16));

        javax.swing.GroupLayout panelResultado2Layout = new javax.swing.GroupLayout(panelResultado2);
        panelResultado2.setLayout(panelResultado2Layout);
        panelResultado2Layout.setHorizontalGroup(
            panelResultado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultado2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(valorInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(valorFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelResultado2Layout.setVerticalGroup(
            panelResultado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultado2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(valorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelResultado1Layout = new javax.swing.GroupLayout(panelResultado1);
        panelResultado1.setLayout(panelResultado1Layout);
        panelResultado1Layout.setHorizontalGroup(
            panelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultado1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelResultado1Layout.setVerticalGroup(
            panelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultado1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelResultado2.setVisible(false);

        valorEntrada.setBackground(new java.awt.Color(233, 232, 248));
        valorEntrada.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        valorEntrada.setForeground(new java.awt.Color(204, 204, 204));
        valorEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valorEntrada.setText("INGRESE EL VALOR A CONVERTIR");
        valorEntrada.setBorder(null);
        valorEntrada.setMaximumSize(new java.awt.Dimension(190, 190));
        valorEntrada.setMinimumSize(new java.awt.Dimension(190, 16));
        valorEntrada.setPreferredSize(new java.awt.Dimension(195, 16));
        valorEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valorEntradaFocusLost(evt);
            }
        });
        valorEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valorEntradaMouseClicked(evt);
            }
        });
        valorEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorEntradaActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        panelBtn1.setBackground(new java.awt.Color(255, 255, 255));

        btn1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn1.setText("CONVERTIR");
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtn1Layout = new javax.swing.GroupLayout(panelBtn1);
        panelBtn1.setLayout(panelBtn1Layout);
        panelBtn1Layout.setHorizontalGroup(
            panelBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtn1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBtn1Layout.setVerticalGroup(
            panelBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(panelBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(valorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelResultado1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(valorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(panelResultado1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorEntradaActionPerformed

    private void valorEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valorEntradaMouseClicked
        valorEntrada.setText("");
        valorEntrada.setForeground(Color.black);
    }//GEN-LAST:event_valorEntradaMouseClicked

    private void btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseEntered
        panelBtn1.setBackground(new Color(223,222,238));
    }//GEN-LAST:event_btn1MouseEntered

    private void btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseExited
        panelBtn1.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn1MouseExited

    private void valorEntradaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorEntradaFocusLost
        if("".equals(valorEntrada.getText()) || valorEntrada.getText() == null){
            valorEntrada.setForeground(new Color(204,204,204));
            valorEntrada.setText("INGRESE EL VALOR A CONVERTIR");
        }
    }//GEN-LAST:event_valorEntradaFocusLost

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        int conversion = tipoDeConversion.getSelectedIndex();
        double tasa;
        switch(conversion){
            case 0:
                tasa = 0.00025;
                resultadoEnPantalla(tasa);
                break;
            case 1:
                tasa = 4040.00;
                resultadoEnPantalla(tasa);
                break;
            case 2:
                tasa = 0.00023;
                resultadoEnPantalla(tasa);
                break;
            case 3:
                tasa = 4407.28;
                resultadoEnPantalla(tasa);
                break;
            case 4:
                tasa = 5125.14;
                resultadoEnPantalla(tasa);
                break;
            case 5:
                tasa = 0.00020;
                resultadoEnPantalla(tasa);
                break;
            case 6:
                tasa = 27.75;
                resultadoEnPantalla(tasa);
                break;
            case 7:
                tasa = 0.037;
                resultadoEnPantalla(tasa);
                break;
            case 8:
                tasa = 0.34;
                resultadoEnPantalla(tasa);
                break;
            case 9:
                tasa = 3.02;
                resultadoEnPantalla(tasa);
                break;
        }
    }//GEN-LAST:event_btn1MouseClicked

    private void tipoDeConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDeConversionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoDeConversionActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }
    
    private void resultadoEnPantalla(double tasa){
        try{
            double valor1 = Double.parseDouble(valorEntrada.getText());
            double valor2;
            double tasaCambio = tasa;
            valorInicial.setText(String.valueOf(valor1));
            valor2 = valor1*tasaCambio;
            valorFinal.setText(String.valueOf(valor2));
            panelResultado2.setVisible(true);
        }catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this, "ese no es un numero valido");
        }finally{
            valorEntrada.setForeground(new Color(204,204,204));
            valorEntrada.setText("INGRESE EL VALOR A CONVERTIR");
        }
    }
    
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("moneda.png"));
        return retValue;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelBtn1;
    private javax.swing.JPanel panelResultado1;
    private javax.swing.JPanel panelResultado2;
    private javax.swing.JComboBox<String> tipoDeConversion;
    private javax.swing.JTextField valorEntrada;
    private javax.swing.JLabel valorFinal;
    private javax.swing.JLabel valorInicial;
    // End of variables declaration//GEN-END:variables
}
